### ISSUE TITLE
[INFO] Fixed compatibility of Jötunn mods

### ISSUE THREAD

**Issue by sirskunkalot** [brandonmousseau/vhvr-mod#118]
Hi @brandonmousseau,

just wanted to report that I have been made aware of the issues your users have with Jötunn mods (I am the dev). Problem was that Jötunn created its own canvas for custom GUI creation for mod devs. That canvas was drawn after Valheim's so it "masked" your changed one, too. I fixed that in the recent version and just inject Jötunn GUI stuff beneath StartGui. Tested and reported working with VHVR.

https://github.com/Valheim-Modding/Jotunn/releases/tag/v2.2.3

btw: I really love your way of creating the BepInEx config GUI. Jötunn creates its own tab in the Settings but I think I will get some inspiration from your way of doing it (if that is OK for you, of course). 

Greetings,
Jules

**Comment by brandonmousseau** [comment]
That's great! Thanks so much! Hopefully this makes a bunch more mods compatible.

Credit to @Andi1986 for the menu configuration - and absolutely no issues if you take a similar approach for Jötunn.

**Comment by sirskunkalot** [comment]
Interestingly this was just a problem with VHVR. Auga for example could handle it without problems. Anyway, it is much cleaner now.

**Comment by Andi1986** [comment]
@sirskunkalot 
Very cool, having compatible mods is great!
About the menu, feel free to use the code, its open source. 
Just as a note, in my implementation all numeric values (floats, ints) need to have AcceptableValueRange as config param in the bepinex config and all Strings need to have AcceptableValueList. I did that because i wanted to avoid having text inputfields especially for VR where typing should be avoided in general. However of course you can add text inputfields aswell.

**Comment by sirskunkalot** [comment]
Thanks, @Andi1986.

Jötunn already features a panel for configs and several setting types. It is kind of messy, though, since we show all configs from all mods using Jötunn in one tab in the vanilla Settings window. That is why I would like to adapt your style here and create my own MenuList with a separate window, having one tab per mod.

If you want to take a look at our implementation: https://github.com/Valheim-Modding/Jotunn/blob/dev/JotunnLib/GUI/InGameConfig.cs
